[project]
name = "fast-ring"
authors = ["FastRing Team"]
description = "Dynamic digital asset tracking and performance management"
telemetry = false
requirements = []
[contracts.ring-vault]
path = "contracts/ring-vault.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
